[build]
  functions = "netlify/functions"
  command = "npm ci && npm run build"
  
[functions]
  node_bundler = "esbuild"

[context.production]
  environment = { ENVIRONMENT = "production" }

  [build]
  command   = "npm ci && npm run build"
  publish   = "dist"                 # usa "build" si tu app es CRA
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# SPA fallback (React Router)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Evitar servir index.html viejo
[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
  Pragma = "no-cache"
  Expires = "0"

# Si usás Vite (assets con hash): pueden quedar cacheados fuerte
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"